return {
  version = "1.11",
  luaversion = "5.1",
  tiledversion = "1.12.2",
  class = "",
  orientation = "orthogonal",
  renderorder = "right-down",
  width = 32,
  height = 12,
  tilewidth = 40,
  tileheight = 40,
  nextlayerid = 8,
  nextobjectid = 40,
  properties = {
    ["name"] = "Scarlet Manor - The Top"
  },
  tilesets = {
    {
      name = "castle",
      firstgid = 1,
      filename = "../tilesets/castle.tsx",
      exportfilename = "../tilesets/castle.lua"
    }
  },
  layers = {
    {
      type = "imagelayer",
      image = "../../../assets/sprites/backgrounds/manor/bg_sky.png",
      id = 8,
      name = "background",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 0,
      parallaxy = 0,
      repeatx = false,
      repeaty = false,
      properties = {}
    },
    {
      type = "imagelayer",
      image = "../../../assets/sprites/backgrounds/bg_battletop.png",
      id = 7,
      name = "background",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      repeatx = false,
      repeaty = false,
      properties = {}
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 3,
      name = "collision",
      class = "",
      visible = true,
      opacity = 0.5,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 2,
          name = "",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 320,
          width = 680,
          height = 40,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 3,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1240,
          y = 320,
          width = 40,
          height = 40,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 7,
          name = "",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 120,
          width = 680,
          height = 40,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 24,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1240,
          y = 120,
          width = 40,
          height = 40,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 48,
          name = "",
          type = "",
          shape = "polygon",
          x = 680,
          y = 320,
          width = 0,
          height = 0,
          rotation = 0,
          opacity = 1,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 0, y = 40 },
            { x = 560, y = 40 },
            { x = 560, y = 0 },
            { x = 520, y = 20 },
            { x = 40, y = 20 }
          },
          properties = {}
        },
        {
          id = 36,
          name = "",
          type = "",
          shape = "polyline",
          x = 710.667,
          y = 339.333,
          width = 0,
          height = 0,
          rotation = 0,
          opacity = 1,
          visible = true,
          polyline = {
            { x = 0, y = 0 },
            { x = -14, y = -2.66667 },
            { x = -18.6667, y = -7.33333 },
            { x = -22.6667, y = -9.33333 },
            { x = -24.6667, y = -10.6667 },
            { x = -27.3333, y = -12.6667 },
            { x = -29.3333, y = -14.6667 },
            { x = -30, y = -17.3333 },
            { x = -32, y = -19.3333 }
          },
          properties = {}
        },
        {
          id = 39,
          name = "",
          type = "",
          shape = "polyline",
          x = 1208,
          y = 340,
          width = 0,
          height = 0,
          rotation = 0,
          opacity = 1,
          visible = true,
          polyline = {
            { x = 0, y = 0 },
            { x = 14, y = -2.66667 },
            { x = 18.6667, y = -7.33333 },
            { x = 22.6667, y = -9.33333 },
            { x = 24.6667, y = -10.6667 },
            { x = 27.3333, y = -12.6667 },
            { x = 29.3333, y = -14.6667 },
            { x = 30, y = -17.3333 },
            { x = 32, y = -19.3333 }
          },
          properties = {}
        },
        {
          id = 37,
          name = "",
          type = "",
          shape = "polyline",
          x = 681.333,
          y = 157.333,
          width = 0,
          height = 0,
          rotation = 0,
          opacity = 1,
          visible = true,
          polyline = {
            { x = 0, y = 0 },
            { x = 8.66667, y = -4 },
            { x = 12.6667, y = -8 },
            { x = 15.3333, y = -12 },
            { x = 18, y = -16.6667 },
            { x = 20, y = -19.3333 },
            { x = 21.3333, y = -22 },
            { x = 22.6667, y = -27.3333 },
            { x = 24.6667, y = -31.3333 },
            { x = 26, y = -34.6667 },
            { x = 27.3333, y = -40 },
            { x = 30.6667, y = -44.6667 },
            { x = 33.3333, y = -48.6667 },
            { x = 38, y = -53.3333 },
            { x = 40, y = -54.6667 },
            { x = 42.6667, y = -58 },
            { x = 46.6667, y = -62 },
            { x = 50, y = -64.6667 },
            { x = 51.3333, y = -66 },
            { x = 54.6667, y = -68.6667 },
            { x = 60, y = -68.6667 },
            { x = 64.6667, y = -69.3333 },
            { x = 66, y = -70 },
            { x = 71.3333, y = -70.6667 },
            { x = 74.6667, y = -74 },
            { x = 77.3333, y = -76 },
            { x = 78, y = -78.6667 }
          },
          properties = {}
        },
        {
          id = 38,
          name = "",
          type = "",
          shape = "polyline",
          x = 1240,
          y = 160,
          width = 0,
          height = 0,
          rotation = 0,
          opacity = 1,
          visible = true,
          polyline = {
            { x = 0, y = 0 },
            { x = -8.66667, y = -4 },
            { x = -12.6667, y = -8 },
            { x = -15.3333, y = -12 },
            { x = -18, y = -16.6667 },
            { x = -20, y = -19.3333 },
            { x = -21.3333, y = -22 },
            { x = -22.6667, y = -27.3333 },
            { x = -24.6667, y = -31.3333 },
            { x = -26, y = -34.6667 },
            { x = -27.3333, y = -40 },
            { x = -30.6667, y = -44.6667 },
            { x = -33.3333, y = -48.6667 },
            { x = -38, y = -53.3333 },
            { x = -40, y = -54.6667 },
            { x = -42.6667, y = -58 },
            { x = -46.6667, y = -62 },
            { x = -50, y = -64.6667 },
            { x = -51.3333, y = -66 },
            { x = -54.6667, y = -68.6667 },
            { x = -60, y = -68.6667 },
            { x = -64.6667, y = -69.3333 },
            { x = -66, y = -70 },
            { x = -71.3333, y = -70.6667 },
            { x = -74.6667, y = -74 },
            { x = -77.3333, y = -76 },
            { x = -78, y = -78.6667 }
          },
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 5,
      name = "objects",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 6,
          name = "npc",
          type = "",
          shape = "rectangle",
          x = 1160,
          y = 200,
          width = 40,
          height = 40,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["actor"] = "remilia"
          }
        },
        {
          id = 9,
          name = "transition",
          type = "",
          shape = "rectangle",
          x = -40,
          y = 160,
          width = 40,
          height = 160,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["map"] = "rm_lake_bridge",
            ["marker"] = "entry_right"
          }
        },
        {
          id = 14,
          name = "savepoint",
          type = "",
          shape = "rectangle",
          x = 80,
          y = 120,
          width = 40,
          height = 40,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["text1"] = "* ",
            ["text2"] = "* "
          }
        },
        {
          id = 32,
          name = "transition",
          type = "",
          shape = "rectangle",
          x = 1280,
          y = 160,
          width = 40,
          height = 160,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["map"] = "rm_intro",
            ["marker"] = "spawn"
          }
        },
        {
          id = 55,
          name = "script",
          type = "",
          shape = "rectangle",
          x = 280,
          y = 160,
          width = 40,
          height = 160,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["cutscene"] = "rm_manor_topbattle.before",
            ["once"] = false
          }
        },
        {
          id = 56,
          name = "npc",
          type = "",
          shape = "rectangle",
          x = 720,
          y = 200,
          width = 40,
          height = 40,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["actor"] = "koakuma"
          }
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 4,
      name = "markers",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 5,
          name = "camera",
          type = "",
          shape = "point",
          x = 960,
          y = 240,
          width = 0,
          height = 0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 8,
          name = "entry",
          type = "",
          shape = "point",
          x = 40,
          y = 240,
          width = 0,
          height = 0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 28,
          name = "spawn",
          type = "",
          shape = "point",
          x = 100,
          y = 240,
          width = 0,
          height = 0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        }
      }
    }
  }
}
